update schools_boundary set name='guledagudda (e)' where id=730;
update schools_boundary set name='guledagudda (w)' where id=9551;
update schools_boundary set name='devanahalli town]' where id=2382;
update schools_boundary set name='krishnananda nagar' where id=8930;
update schools_boundary set name='rajajinagara' where id=9008;
update schools_boundary set name='sri rampuram' where id=8923;
update schools_boundary set name='p0try town' where id=8948;
update schools_boundary set name='abbigerie' where id=9000;
update schools_boundary set name='aggarahara layout' where id=8999;
update schools_boundary set name='byataranpura' where id=8906;
update schools_boundary set name='doodda byalakere' where id=8915;
update schools_boundary set name='mthahalli' where id=9001;
update schools_boundary set name='yelahanka new town' where id=8962;
update schools_boundary set name='yelahanka old town' where id=8966;
update schools_boundary set name='chendapura' where id=9161;
update schools_boundary set name='huskur]' where id=8960;
update schools_boundary set name='kumbalgodu' where id=8891;
update schools_boundary set name='byataranapura' where id=8892;
update schools_boundary set name='chamrajpete' where id=8902;
update schools_boundary set name='astin town' where id=9539;
update schools_boundary set name='eejepura' where id=8912;
update schools_boundary set name='sambaragi' where id=3088;
update schools_boundary set name='shirahatti' where id=3090;
update schools_boundary set name='ankalagi' where id=3110;
update schools_boundary set name='khanagaon' where id=3109;
update schools_boundary set name='mamadapur' where id=3111;
update schools_boundary set name='hadagali gramina' where id=1521;
update schools_boundary set name='15th ward, hospet' where id=1531;
update schools_boundary set name='8th ward, kampli' where id=9438;
update schools_boundary set name='ambedkar,j.rd.hpt.' where id=1532;
update schools_boundary set name='s.n.pet,  kampli' where id=1542;
update schools_boundary set name='vinobha,chithawadgi hpt' where id=1545;
update schools_boundary set name='kottur, lbs badavane' where id=1560;
update schools_boundary set name='kudligi, for boys' where id=1551;
update schools_boundary set name='kudligi, for girls' where id=1552;
update schools_boundary set name='ujjini, for girls' where id=1553;
update schools_boundary set name='siruguppa, 5th ward' where id=1573;
update schools_boundary set name='siruguppa, 6th ward' where id=1574;
update schools_boundary set name='dhannura (s)' where id=1021;
update schools_boundary set name='kbs no. 26 jala nagar' where id=9589;
update schools_boundary set name='chamarajanagar-1v' where id=9630;
update schools_boundary set name='duggahatti' where id=2901;
update schools_boundary set name='bagepalli rural' where id=3020;
update schools_boundary set name='abloodu' where id=3072;
update schools_boundary set name='shidlaghatta' where id=3075;
update schools_boundary set name='mugathihalli - 01' where id=2029;
update schools_boundary set name='makonahalli' where id=2050;
update schools_boundary set name='bheemasamudra' where id=1604;
update schools_boundary set name='chikkabennuru' where id=1610;
update schools_boundary set name='godabanahal' where id=1603;
update schools_boundary set name='hiriyur  north' where id=1630;
update schools_boundary set name='s.neralakere' where id=1659;
update schools_boundary set name='kerebilachi' where id=1690;
update schools_boundary set name='santhebennuru-1' where id=1693;
update schools_boundary set name='mayakonda' where id=1724;
update schools_boundary set name='harapanahalli-north' where id=1779;
update schools_boundary set name='mathihalli' where id=1767;
update schools_boundary set name='urdu honnali-1' where id=1754;
update schools_boundary set name='donnehalli' where id=1759;
update schools_boundary set name='gandhi chouk' where id=9134;
update schools_boundary set name='madarmaddi kan dwd' where id=1282;
update schools_boundary set name='malamaddi dharwad' where id=1281;
update schools_boundary set name='sadashivnagar' where id=9142;
update schools_boundary set name='gudageri' where id=1261;
update schools_boundary set name='hulkoti' where id=1222;
update schools_boundary set name='mulagund' where id=1218;
update schools_boundary set name='soratur' where id=1225;
update schools_boundary set name='hirewaddtti' where id=9110;
update schools_boundary set name='lakshmeshwar north' where id=1214;
update schools_boundary set name='baluragi' where id=9263;
update schools_boundary set name='deval gangapur' where id=893;
update schools_boundary set name='chimmanchod' where id=904;
update schools_boundary set name='madaboola' where id=925;
update schools_boundary set name='revaggi' where id=922;
update schools_boundary set name='chalageri' where id=1471;
update schools_boundary set name='gudihonatti' where id=1474;
update schools_boundary set name='haranagiri' where id=1475;
update schools_boundary set name='bhagamandala' where id=2717;
update schools_boundary set name='murnadu' where id=2722;
update schools_boundary set name='napoklu' where id=2723;
update schools_boundary set name='polibetta' where id=2744;
update schools_boundary set name='boodagumpa' where id=1152;
update schools_boundary set name='killarahatti' where id=9108;
update schools_boundary set name='mudenoor' where id=1158;
update schools_boundary set name='sanganahal' where id=9105;
update schools_boundary set name='tavaragera' where id=1159;
update schools_boundary set name='hirevankalakunta' where id=1167;
update schools_boundary set name='kukanoor' where id=1169;
update schools_boundary set name='mangalore' where id=1170;
update schools_boundary set name='talakal' where id=1172;
update schools_boundary set name='yelaburga' where id=1173;
update schools_boundary set name='gandhinagara' where id=2410;
update schools_boundary set name='chikkaarasinakere' where id=2416;
update schools_boundary set name='shivalli' where id=2513;
update schools_boundary set name='mandya 03' where id=2463;
update schools_boundary set name='bogadi' where id=2478;
update schools_boundary set name='brahmadevara hally' where id=2467;
update schools_boundary set name='koochahalli' where id=2481;
update schools_boundary set name='chinakurali' where id=2483;
update schools_boundary set name='ragimuddanahalli' where id=2492;
update schools_boundary set name='sunka thonnuru' where id=2491;
update schools_boundary set name='rajivnagara(urdu' where id=9189;
update schools_boundary set name='vinyakanagara' where id=9186;
update schools_boundary set name='devala pura' where id=9024;
update schools_boundary set name='muguru' where id=9030;
update schools_boundary set name='santekellur' where id=1079;
update schools_boundary set name='potnal' where id=1096;
update schools_boundary set name='devi camp' where id=9406;
update schools_boundary set name='gudadur' where id=1114;
update schools_boundary set name='hosahalli (ej)' where id=1122;
update schools_boundary set name='rh no-1' where id=9414;
update schools_boundary set name='shri venkteswara camp' where id=1119;
update schools_boundary set name='bannikuppe(b)' where id=3250;
update schools_boundary set name='isur' where id=1832;
update schools_boundary set name='kasaba shikaripur-2' where id=1838;
update schools_boundary set name='durvaspura' where id=1868;
update schools_boundary set name='baragur' where id=2089;
update schools_boundary set name='hoysala katte' where id=2095;
update schools_boundary set name='kandhikere' where id=2096;
update schools_boundary set name='mathighatta' where id=2088;
update schools_boundary set name='shettykere' where id=2092;
update schools_boundary set name='chelur' where id=2106;
update schools_boundary set name='hagalavadi' where id=2109;
update schools_boundary set name='hpbs gubbi' where id=2097;
update schools_boundary set name='ujjani' where id=2154;
update schools_boundary set name='byranayakanahalli' where id=2136;
update schools_boundary set name='halukurike' where id=2126;
update schools_boundary set name='kote nayakanahalli' where id=2135;
update schools_boundary set name='highschool extn.' where id=2150;
update schools_boundary set name='north extn.' where id=2146;
update schools_boundary set name='urdigere' where id=2139;
update schools_boundary set name='kanathur' where id=2118;
update schools_boundary set name='avarse' where id=1956;
update schools_boundary set name='saibarkatte' where id=1946;
update schools_boundary set name='are shiroor' where id=1941;
update schools_boundary set name='shiroor' where id=1939;
update schools_boundary set name='kundapura' where id=1921;
update schools_boundary set name='athradi' where id=1897;
update schools_boundary set name='kalathuru' where id=1899;
update schools_boundary set name='aggaragone' where id=1307;
update schools_boundary set name='aversa' where id=1305;
update schools_boundary set name='bobruwada' where id=1298;
update schools_boundary set name='bailur' where id=1394;
update schools_boundary set name='mavinakatte' where id=1397;
update schools_boundary set name='nawayath colony' where id=1405;
update schools_boundary set name='balkur' where id=1384;
update schools_boundary set name='chikkanakod' where id=1392;
update schools_boundary set name='honnavar' where id=1381;
update schools_boundary set name='kasarakod' where id=1382;
update schools_boundary set name='maagod' where id=1389;
update schools_boundary set name='handigona' where id=1346;
update schools_boundary set name='hegde' where id=1350;
update schools_boundary set name='kagal' where id=1344;
update schools_boundary set name='dodnalli' where id=1325;
update schools_boundary set name='vanalli' where id=1328;
update schools_boundary set name='anagod' where id=1376;
update schools_boundary set name='vajralli' where id=1375;
update schools_boundary set name='doranahalli' where id=3294;
update schools_boundary set name='shirwal' where id=3299;
update schools_boundary set name='geddalmari' where id=9458;
update schools_boundary set name='anpur' where id=9474;
update schools_boundary set name='arakera(k)' where id=9466;
update schools_boundary set name='balichakra' where id=3328;
update schools_boundary set name='gurumitkal' where id=3331;
update schools_boundary set name='madhawar' where id=3336;
update schools_boundary set name='yelheri' where id=3338;
update schools_boundary set name='yergole' where id=3339;

